// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Raven.Api.Data;

#nullable disable

namespace Raven.Api.Data.Migrations
{
    [DbContext(typeof(RavenDbContext))]
    [Migration("20260911072055_AddCompanyMonitoring")]
    partial class AddCompanyMonitoring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Raven.Api.Features.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Headquarters")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastResearchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Raven.Api.Features.Monitoring.CompanyMonitoringSetting", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveClaimId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ClaimExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastRunStatus")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("NextRunAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyId");

                    b.HasIndex("ClaimExpiresAt");

                    b.HasIndex("Enabled", "NextRunAt");

                    b.ToTable("CompanyMonitoringSettings");
                });

            modelBuilder.Entity("Raven.Api.Features.Profiles.Changes.ProfileChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldPath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemKey")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NewProfileVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValueJson")
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OldProfileVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValueJson")
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "DetectedAt");

                    b.HasIndex("CompanyId", "NewProfileVersionId");

                    b.ToTable("ProfileChanges");
                });

            modelBuilder.Entity("Raven.Api.Features.Profiles.CompanyProfileCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AiModel")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AiProvider")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptTemplateVersion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResearchRunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResearchRunId", "GeneratedAt");

                    b.ToTable("CompanyProfileCandidates");
                });

            modelBuilder.Entity("Raven.Api.Features.Profiles.CompanyProfileVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AiModel")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AiProvider")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptTemplateVersion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResearchRunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "ConfirmedAt");

                    b.HasIndex("CompanyId", "Version")
                        .IsUnique();

                    b.ToTable("CompanyProfileVersions");
                });

            modelBuilder.Entity("Raven.Api.Features.Profiles.ProfileEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CompanyProfileCandidateId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CompanyProfileVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldPath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDocumentIdsJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyProfileVersionId", "FieldPath");

                    b.ToTable("ProfileEvidences");
                });

            modelBuilder.Entity("Raven.Api.Features.Research.Events.ResearchEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CachedTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalRequestId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InputHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("InputSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PromptTemplateVersion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResearchRunId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResearchRunId", "Sequence");

                    b.ToTable("ResearchEvents");
                });

            modelBuilder.Entity("Raven.Api.Features.Research.Intelligence.ResearchIdentityCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficialDomain")
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rationale")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Recommended")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelationshipHint")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResearchRunId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Selected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupportingCandidateIdsJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TemporaryId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResearchRunId", "TemporaryId")
                        .IsUnique();

                    b.ToTable("ResearchIdentityCandidates");
                });

            modelBuilder.Entity("Raven.Api.Features.Research.ResearchCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AcquisitionError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("AcquisitionStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DiscoveredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendationReasonsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Recommended")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ResearchRunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SearchRank")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Selected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Snippet")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResearchRunId", "NormalizedUrl")
                        .IsUnique();

                    b.ToTable("ResearchCandidates");
                });

            modelBuilder.Entity("Raven.Api.Features.Research.ResearchRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualCrawlerProvider")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualSearchProvider")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CrawlCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrawlFailed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrawlSucceeded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrawlTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentsAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuplicatesSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroundingMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("QueriesCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueriesTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecommendedCandidates")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestedCrawlerProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedSearchProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResearchHint")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResolvedIdentityCandidateId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourcesCrawled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourcesFound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourcesSelected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("UniqueCandidates")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "StartedAt");

                    b.ToTable("ResearchRuns");
                });

            modelBuilder.Entity("Raven.Api.Features.Research.SourceDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CrawlerProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResearchRunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDomain")
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("StructuredFactsJson")
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResearchRunId");

                    b.HasIndex("CompanyId", "ContentHash");

                    b.HasIndex("CompanyId", "NormalizedUrl");

                    b.ToTable("SourceDocuments");
                });

            modelBuilder.Entity("Raven.Api.Features.Settings.ResearchSettingsEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AiSourceRerankingEnabled")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("CrawlerProviderPriority")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeepResearchModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroundingMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroundingModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderPreset")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("SearchProviderPriority")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ResearchSettings");
                });

            modelBuilder.Entity("Raven.Api.Features.Monitoring.CompanyMonitoringSetting", b =>
                {
                    b.HasOne("Raven.Api.Features.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Raven.Api.Features.Research.Intelligence.ResearchIdentityCandidate", b =>
                {
                    b.HasOne("Raven.Api.Features.Research.ResearchRun", null)
                        .WithMany()
                        .HasForeignKey("ResearchRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Raven.Api.Features.Research.ResearchCandidate", b =>
                {
                    b.HasOne("Raven.Api.Features.Research.ResearchRun", "ResearchRun")
                        .WithMany("Candidates")
                        .HasForeignKey("ResearchRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResearchRun");
                });

            modelBuilder.Entity("Raven.Api.Features.Research.ResearchRun", b =>
                {
                    b.HasOne("Raven.Api.Features.Companies.Company", "Company")
                        .WithMany("ResearchRuns")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Raven.Api.Features.Research.SourceDocument", b =>
                {
                    b.HasOne("Raven.Api.Features.Companies.Company", "Company")
                        .WithMany("SourceDocuments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Raven.Api.Features.Research.ResearchRun", "ResearchRun")
                        .WithMany("SourceDocuments")
                        .HasForeignKey("ResearchRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("ResearchRun");
                });

            modelBuilder.Entity("Raven.Api.Features.Companies.Company", b =>
                {
                    b.Navigation("ResearchRuns");

                    b.Navigation("SourceDocuments");
                });

            modelBuilder.Entity("Raven.Api.Features.Research.ResearchRun", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("SourceDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
