// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Raven.Api.Data;

#nullable disable

namespace Raven.Api.Data.Migrations
{
    [DbContext(typeof(RavenDbContext))]
    [Migration("20260910100504_AddCompanyIdentityDetails")]
    partial class AddCompanyIdentityDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Raven.Api.Features.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Headquarters")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastResearchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Raven.Api.Features.Research.ResearchRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualCrawlerProvider")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualSearchProvider")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedCrawlerProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedSearchProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourcesCrawled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourcesFound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourcesSelected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "StartedAt");

                    b.ToTable("ResearchRuns");
                });

            modelBuilder.Entity("Raven.Api.Features.Research.SourceDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CrawlerProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResearchRunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDomain")
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResearchRunId");

                    b.HasIndex("CompanyId", "ContentHash");

                    b.HasIndex("CompanyId", "NormalizedUrl");

                    b.ToTable("SourceDocuments");
                });

            modelBuilder.Entity("Raven.Api.Features.Research.ResearchRun", b =>
                {
                    b.HasOne("Raven.Api.Features.Companies.Company", "Company")
                        .WithMany("ResearchRuns")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Raven.Api.Features.Research.SourceDocument", b =>
                {
                    b.HasOne("Raven.Api.Features.Companies.Company", "Company")
                        .WithMany("SourceDocuments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Raven.Api.Features.Research.ResearchRun", "ResearchRun")
                        .WithMany("SourceDocuments")
                        .HasForeignKey("ResearchRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("ResearchRun");
                });

            modelBuilder.Entity("Raven.Api.Features.Companies.Company", b =>
                {
                    b.Navigation("ResearchRuns");

                    b.Navigation("SourceDocuments");
                });

            modelBuilder.Entity("Raven.Api.Features.Research.ResearchRun", b =>
                {
                    b.Navigation("SourceDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
