using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using Raven.Api.Features.Research.SavedArtifacts;

namespace Raven.Api.Features.Research.ExternalImport;

/// <summary>
/// Tolerant parser for the Markdown format generated by
/// <see cref="ExternalResearchBriefGenerator"/>. It deliberately produces
/// reviewable notes and URL leads only; it never creates SourceDocument or
/// ProfileEvidence rows.
/// </summary>
public sealed partial class ExternalResearchImportParser : IExternalResearchImportParser
{
    private static readonly HashSet<string> SectionNames = new(StringComparer.OrdinalIgnoreCase)
    {
        "research summary",
        "summary",
        "claims",
        "sources",
        "uncertainties",
        "suggested follow-up",
        "suggested follow-ups",
        "follow-up",
        "follow-ups"
    };

    public ExternalResearchImportResult Parse(string markdown)
    {
        ArgumentNullException.ThrowIfNull(markdown);

        var summaryLines = new List<string>();
        var uncertainties = new List<string>();
        var followUps = new List<string>();
        var claimDrafts = new List<ClaimDraft>();
        var sourceDrafts = new List<SourceDraft>();
        var section = Section.Unknown;
        ClaimDraft? currentClaim = null;
        SourceDraft? currentSource = null;

        foreach (var rawLine in markdown.Replace("\r\n", "\n", StringComparison.Ordinal).Replace('\r', '\n').Split('\n'))
        {
            var line = rawLine.Trim();
            if (line.Length == 0 || IsMarkdownSeparator(line))
            {
                continue;
            }

            if (TryReadSection(line, out var nextSection))
            {
                FlushClaim(currentClaim, claimDrafts);
                currentClaim = null;
                FlushSource(currentSource, sourceDrafts);
                currentSource = null;
                section = nextSection;
                continue;
            }

            // Users often paste the body without the generated section
            // headings. Recognize the structured labels as an implicit section
            // boundary while retaining any preceding prose as the summary.
            if (section == Section.Unknown && TryReadKeyValue(line, out var implicitKey, out _))
            {
                var normalizedImplicitKey = NormalizeKey(implicitKey);
                if (normalizedImplicitKey is "field" or "claim" or "statement" or "supporting urls" or "supporting sources" or "urls" or "confidence" or "notes" or "note")
                {
                    section = Section.Claims;
                }
                else if (normalizedImplicitKey is "title" or "url" or "link" or "publisher" or "domain" or "date" or "published" or "updated" or "published updated" or "supports" or "supports claims" or "source type" or "type")
                {
                    section = Section.Sources;
                }
            }

            switch (section)
            {
                case Section.Summary:
                    AddText(summaryLines, StripListMarker(line));
                    break;
                case Section.Claims:
                    currentClaim = ReadClaimLine(line, currentClaim, claimDrafts);
                    break;
                case Section.Sources:
                    currentSource = ReadSourceLine(line, currentSource, sourceDrafts);
                    break;
                case Section.Uncertainties:
                    AddText(uncertainties, StripListMarker(line));
                    break;
                case Section.FollowUps:
                    AddText(followUps, StripListMarker(line));
                    break;
                case Section.Unknown:
                    // A missing "Research Summary" heading is common when a
                    // user edits the response. Preserve preamble text rather
                    // than silently discarding it.
                    if (!LooksLikeTemplateInstruction(line))
                    {
                        AddText(summaryLines, StripListMarker(line));
                    }
                    break;
            }
        }

        FlushClaim(currentClaim, claimDrafts);
        FlushSource(currentSource, sourceDrafts);

        var sourceLeads = BuildSourceLeads(sourceDrafts, claimDrafts);
        var leadsByUrl = sourceLeads.ToDictionary(lead => NormalizeUrl(lead.Url), StringComparer.OrdinalIgnoreCase);
        var claims = claimDrafts
            .Select(draft => ToClaim(draft, leadsByUrl))
            .Where(claim => claim is not null)
            .Cast<ResearchClaim>()
            .ToArray();

        return new ExternalResearchImportResult(
            string.Join(Environment.NewLine, summaryLines).Trim(),
            claims,
            sourceLeads,
            DistinctNonBlank(uncertainties),
            DistinctNonBlank(followUps),
            markdown);
    }

    private static ClaimDraft? ReadClaimLine(string line, ClaimDraft? current, ICollection<ClaimDraft> completed)
    {
        var value = StripListMarker(line);
        if (TryReadKeyValue(value, out var key, out var fieldValue))
        {
            switch (NormalizeKey(key))
            {
                case "field":
                    if (current is not null && (current.Field.Length > 0 || current.Statement.Length > 0))
                    {
                        completed.Add(current);
                    }

                    return new ClaimDraft { Field = CleanValue(fieldValue) };
                case "claim":
                case "statement":
                    current ??= new ClaimDraft();
                    current.Statement = CleanValue(fieldValue);
                    return current;
                case "supporting urls":
                case "supporting sources":
                case "urls":
                    current ??= new ClaimDraft();
                    current.Urls.AddRange(ExtractUrls(fieldValue));
                    return current;
                case "confidence":
                    current ??= new ClaimDraft();
                    current.Confidence = CleanValue(fieldValue);
                    return current;
                case "notes":
                case "note":
                    current ??= new ClaimDraft();
                    current.Notes = CleanValue(fieldValue);
                    return current;
            }
        }

        var urls = ExtractUrls(value);
        if (urls.Count > 0)
        {
            current ??= new ClaimDraft();
            current.Urls.AddRange(urls);
            return current;
        }

        if (current is not null && value.Length > 0)
        {
            current.Statement = string.IsNullOrWhiteSpace(current.Statement)
                ? CleanValue(value)
                : $"{current.Statement} {CleanValue(value)}";
            return current;
        }

        return current;
    }

    private static SourceDraft? ReadSourceLine(string line, SourceDraft? current, ICollection<SourceDraft> completed)
    {
        var value = StripListMarker(line);
        if (TryReadKeyValue(value, out var key, out var fieldValue))
        {
            var normalizedKey = NormalizeKey(key);
            if (normalizedKey is "title" && current is not null && current.HasContent)
            {
                completed.Add(current);
                current = null;
            }

            current ??= new SourceDraft();
            switch (normalizedKey)
            {
                case "title":
                    current.Title = CleanValue(fieldValue);
                    break;
                case "url":
                case "link":
                    current.Url = ExtractUrls(fieldValue).FirstOrDefault() ?? CleanValue(fieldValue);
                    break;
                case "publisher":
                case "domain":
                    current.Publisher = CleanValue(fieldValue);
                    break;
                case "date":
                case "published":
                case "updated":
                case "published updated":
                    current.PublishedAt = ParseDate(fieldValue);
                    break;
                case "supports":
                case "supports claims":
                    current.Supports = CleanValue(fieldValue);
                    break;
                case "source type":
                case "type":
                    current.SourceType = CleanValue(fieldValue);
                    break;
            }

            return current;
        }

        var url = ExtractUrls(value).FirstOrDefault();
        if (url is not null)
        {
            if (current is not null && current.Url is not null)
            {
                completed.Add(current);
                current = null;
            }

            current ??= new SourceDraft();
            current.Url = url;
        }

        return current;
    }

    private static void FlushClaim(ClaimDraft? draft, ICollection<ClaimDraft> completed)
    {
        if (draft is not null && (draft.Field.Length > 0 || draft.Statement.Length > 0 || draft.Urls.Count > 0))
        {
            completed.Add(draft);
        }
    }

    private static void FlushSource(SourceDraft? draft, ICollection<SourceDraft> completed)
    {
        if (draft is not null && draft.HasContent)
        {
            completed.Add(draft);
        }
    }

    private static IReadOnlyList<ResearchSourceLead> BuildSourceLeads(
        IEnumerable<SourceDraft> sourceDrafts,
        IEnumerable<ClaimDraft> claimDrafts)
    {
        var leads = new List<ResearchSourceLead>();
        var byUrl = new Dictionary<string, ResearchSourceLead>(StringComparer.OrdinalIgnoreCase);

        foreach (var draft in sourceDrafts)
        {
            AddLead(draft.Url, draft.Title, draft.Publisher, draft.PublishedAt, draft.SourceType, draft.Supports, byUrl, leads);
        }

        foreach (var url in claimDrafts.SelectMany(draft => draft.Urls))
        {
            AddLead(url, null, null, null, null, null, byUrl, leads);
        }

        return leads;
    }

    private static void AddLead(
        string? rawUrl,
        string? title,
        string? publisher,
        DateTimeOffset? publishedAt,
        string? sourceType,
        string? supports,
        IDictionary<string, ResearchSourceLead> byUrl,
        ICollection<ResearchSourceLead> leads)
    {
        var url = ExtractUrls(rawUrl ?? string.Empty).FirstOrDefault();
        if (url is null || !Uri.TryCreate(url, UriKind.Absolute, out var uri) || uri.Scheme is not ("http" or "https"))
        {
            return;
        }

        var normalizedUrl = NormalizeUrl(url);
        if (byUrl.TryGetValue(normalizedUrl, out var existing))
        {
            if (existing.Title is null && !string.IsNullOrWhiteSpace(title) ||
                existing.Publisher is null && !string.IsNullOrWhiteSpace(publisher) ||
                existing.PublishedAt is null && publishedAt is not null ||
                existing.SourceType is null && !string.IsNullOrWhiteSpace(sourceType) ||
                existing.Supports is null && !string.IsNullOrWhiteSpace(supports))
            {
                var enriched = existing with
                {
                    Title = existing.Title ?? NullIfBlank(title),
                    Publisher = existing.Publisher ?? NullIfBlank(publisher) ?? uri.Host,
                    PublishedAt = existing.PublishedAt ?? publishedAt,
                    SourceType = existing.SourceType ?? NullIfBlank(sourceType),
                    Supports = existing.Supports ?? NullIfBlank(supports)
                };
                byUrl[normalizedUrl] = enriched;
                var index = leads.ToList().FindIndex(lead => lead.Id == existing.Id);
                if (index >= 0)
                {
                    var list = (List<ResearchSourceLead>)leads;
                    list[index] = enriched;
                }
            }

            return;
        }

        var lead = new ResearchSourceLead(
            url,
            NullIfBlank(title),
            NullIfBlank(publisher) ?? uri.Host,
            publishedAt,
            NullIfBlank(sourceType),
            NullIfBlank(supports));
        byUrl[normalizedUrl] = lead;
        leads.Add(lead);
    }

    private static ResearchClaim? ToClaim(ClaimDraft draft, IReadOnlyDictionary<string, ResearchSourceLead> leadsByUrl)
    {
        if (string.IsNullOrWhiteSpace(draft.Statement) && draft.Urls.Count == 0)
        {
            return null;
        }

        var sourceLeadIds = draft.Urls
            .Select(NormalizeUrl)
            .Where(leadsByUrl.ContainsKey)
            .Select(url => leadsByUrl[url].Id)
            .Distinct()
            .ToArray();
        return new ResearchClaim(
            string.IsNullOrWhiteSpace(draft.Field) ? "Unspecified" : draft.Field.Trim(),
            string.IsNullOrWhiteSpace(draft.Statement) ? "Source lead supplied without a claim statement." : draft.Statement.Trim(),
            sourceLeadIds,
            NullIfBlank(draft.Confidence),
            NullIfBlank(draft.Notes));
    }

    private static bool TryReadSection(string line, out Section section)
    {
        var candidate = line.Trim().TrimStart('#').Trim();
        candidate = TrimMarkdown(candidate).TrimEnd(':').Trim();
        if (!SectionNames.Contains(candidate))
        {
            section = Section.Unknown;
            return false;
        }

        section = NormalizeKey(candidate) switch
        {
            "research summary" or "summary" => Section.Summary,
            "claims" => Section.Claims,
            "sources" => Section.Sources,
            "uncertainties" => Section.Uncertainties,
            _ => Section.FollowUps
        };
        return true;
    }

    private static bool TryReadKeyValue(string line, out string key, out string value)
    {
        var colon = line.IndexOf(':');
        if (colon <= 0)
        {
            key = string.Empty;
            value = string.Empty;
            return false;
        }

        key = TrimMarkdown(line[..colon]).Trim();
        value = line[(colon + 1)..].Trim();
        return key.Length > 0;
    }

    private static string StripListMarker(string line)
    {
        var value = line.Trim();
        if (value.StartsWith("- ", StringComparison.Ordinal) || value.StartsWith("* ", StringComparison.Ordinal) || value.StartsWith("+ ", StringComparison.Ordinal))
        {
            return value[2..].Trim();
        }

        var index = 0;
        while (index < value.Length && char.IsDigit(value[index])) index++;
        if (index > 0 && index < value.Length && value[index] == '.')
        {
            return value[(index + 1)..].Trim();
        }

        return value;
    }

    private static void AddText(ICollection<string> values, string? value)
    {
        var normalized = NullIfBlank(value);
        if (normalized is not null)
        {
            values.Add(normalized);
        }
    }

    private static string NormalizeKey(string value) =>
        TrimMarkdown(value).Trim().TrimEnd(':').Replace('-', ' ').Replace('_', ' ').ToLowerInvariant() switch
        {
            "supporting url" => "supporting urls",
            "supporting links" => "supporting urls",
            "published/updated date" => "published updated",
            "suggested follow up" => "suggested follow-up",
            "suggested follow ups" => "suggested follow-ups",
            _ => TrimMarkdown(value).Trim().TrimEnd(':').Replace('-', ' ').Replace('_', ' ').ToLowerInvariant()
        };

    private static string TrimMarkdown(string value) => value.Trim().Trim('*', '_', '`', ' ', '\t');

    private static string CleanValue(string value) => TrimMarkdown(value).Trim();

    private static string? NullIfBlank(string? value) => string.IsNullOrWhiteSpace(value) ? null : value.Trim();

    private static List<string> ExtractUrls(string value) =>
        UrlRegex().Matches(value)
            .Select(match => match.Value.TrimEnd('.', ',', ';', ':', ')', ']', '>'))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();

    private static DateTimeOffset? ParseDate(string value) =>
        DateTimeOffset.TryParse(CleanValue(value), CultureInfo.InvariantCulture, DateTimeStyles.AssumeUniversal, out var date)
            ? date
            : null;

    private static string NormalizeUrl(string url) =>
        Uri.TryCreate(url, UriKind.Absolute, out var uri)
            ? uri.GetComponents(UriComponents.SchemeAndServer | UriComponents.PathAndQuery, UriFormat.UriEscaped).TrimEnd('/').ToLowerInvariant()
            : url.Trim().ToLowerInvariant();

    private static bool IsMarkdownSeparator(string line) =>
        line.All(character => character is '-' or '*' or '_' or ' ');

    private static bool LooksLikeTemplateInstruction(string line) =>
        line.StartsWith("<", StringComparison.Ordinal) && line.EndsWith(">", StringComparison.Ordinal);

    private static IReadOnlyList<string> DistinctNonBlank(IEnumerable<string> values) =>
        values.Select(NullIfBlank).Where(value => value is not null).Cast<string>().Distinct(StringComparer.OrdinalIgnoreCase).ToArray();

    [GeneratedRegex("https?://[^\\s)\\]}>]+", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex UrlRegex();

    private enum Section
    {
        Unknown,
        Summary,
        Claims,
        Sources,
        Uncertainties,
        FollowUps
    }

    private sealed class ClaimDraft
    {
        public string Field { get; set; } = string.Empty;
        public string Statement { get; set; } = string.Empty;
        public string? Confidence { get; set; }
        public string? Notes { get; set; }
        public List<string> Urls { get; } = [];
    }

    private sealed class SourceDraft
    {
        public string? Url { get; set; }
        public string? Title { get; set; }
        public string? Publisher { get; set; }
        public DateTimeOffset? PublishedAt { get; set; }
        public string? SourceType { get; set; }
        public string? Supports { get; set; }
        public bool HasContent => Url is not null || Title is not null || Publisher is not null;
    }
}
